<?php
/**
 * AppAssociations
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Bitly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bitly API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bitly\Model;

use \ArrayAccess;
use \Bitly\ObjectSerializer;

/**
 * AppAssociations Class Doc Comment
 *
 * @category Class
 * @package  Bitly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class AppAssociations implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AppAssociations';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'android_install_preference' => '\Bitly\Model\InstallPreference',
        'ios_install_preference' => '\Bitly\Model\InstallPreference',
        'android_apps' => '\Bitly\Model\AppAssociationDetail[]',
        'custom_domain' => 'string',
        'ios_apps' => '\Bitly\Model\AppAssociationDetail[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'android_install_preference' => null,
        'ios_install_preference' => null,
        'android_apps' => null,
        'custom_domain' => null,
        'ios_apps' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'android_install_preference' => 'android_install_preference',
        'ios_install_preference' => 'ios_install_preference',
        'android_apps' => 'android_apps',
        'custom_domain' => 'custom_domain',
        'ios_apps' => 'ios_apps'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'android_install_preference' => 'setAndroidInstallPreference',
        'ios_install_preference' => 'setIosInstallPreference',
        'android_apps' => 'setAndroidApps',
        'custom_domain' => 'setCustomDomain',
        'ios_apps' => 'setIosApps'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'android_install_preference' => 'getAndroidInstallPreference',
        'ios_install_preference' => 'getIosInstallPreference',
        'android_apps' => 'getAndroidApps',
        'custom_domain' => 'getCustomDomain',
        'ios_apps' => 'getIosApps'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['android_install_preference'] = $data['android_install_preference'] ?? null;
        $this->container['ios_install_preference'] = $data['ios_install_preference'] ?? null;
        $this->container['android_apps'] = $data['android_apps'] ?? null;
        $this->container['custom_domain'] = $data['custom_domain'] ?? null;
        $this->container['ios_apps'] = $data['ios_apps'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets android_install_preference
     *
     * @return \Bitly\Model\InstallPreference|null
     */
    public function getAndroidInstallPreference()
    {
        return $this->container['android_install_preference'];
    }

    /**
     * Sets android_install_preference
     *
     * @param \Bitly\Model\InstallPreference|null $android_install_preference android_install_preference
     *
     * @return self
     */
    public function setAndroidInstallPreference($android_install_preference)
    {
        $this->container['android_install_preference'] = $android_install_preference;

        return $this;
    }

    /**
     * Gets ios_install_preference
     *
     * @return \Bitly\Model\InstallPreference|null
     */
    public function getIosInstallPreference()
    {
        return $this->container['ios_install_preference'];
    }

    /**
     * Sets ios_install_preference
     *
     * @param \Bitly\Model\InstallPreference|null $ios_install_preference ios_install_preference
     *
     * @return self
     */
    public function setIosInstallPreference($ios_install_preference)
    {
        $this->container['ios_install_preference'] = $ios_install_preference;

        return $this;
    }

    /**
     * Gets android_apps
     *
     * @return \Bitly\Model\AppAssociationDetail[]|null
     */
    public function getAndroidApps()
    {
        return $this->container['android_apps'];
    }

    /**
     * Sets android_apps
     *
     * @param \Bitly\Model\AppAssociationDetail[]|null $android_apps android_apps
     *
     * @return self
     */
    public function setAndroidApps($android_apps)
    {
        $this->container['android_apps'] = $android_apps;

        return $this;
    }

    /**
     * Gets custom_domain
     *
     * @return string|null
     */
    public function getCustomDomain()
    {
        return $this->container['custom_domain'];
    }

    /**
     * Sets custom_domain
     *
     * @param string|null $custom_domain custom_domain
     *
     * @return self
     */
    public function setCustomDomain($custom_domain)
    {
        $this->container['custom_domain'] = $custom_domain;

        return $this;
    }

    /**
     * Gets ios_apps
     *
     * @return \Bitly\Model\AppAssociationDetail[]|null
     */
    public function getIosApps()
    {
        return $this->container['ios_apps'];
    }

    /**
     * Sets ios_apps
     *
     * @param \Bitly\Model\AppAssociationDetail[]|null $ios_apps ios_apps
     *
     * @return self
     */
    public function setIosApps($ios_apps)
    {
        $this->container['ios_apps'] = $ios_apps;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


