<?php
/**
 * ChannelBitlink
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  Bitly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bitly API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Bitly\Model;

use \ArrayAccess;
use \Bitly\ObjectSerializer;

/**
 * ChannelBitlink Class Doc Comment
 *
 * @category Class
 * @package  Bitly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class ChannelBitlink implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ChannelBitlink';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'keyword_link' => 'string',
        'created_ts' => 'int',
        'bitlink_id' => 'string',
        'channel_guid' => 'string',
        'title' => 'string',
        'campaign_ids' => 'string[]',
        'total_clicks' => 'int',
        'aggregate_link' => 'string',
        'campaign_guid' => 'string',
        'link' => 'string',
        'client_id' => 'string',
        'long_url' => 'string',
        'clicks' => '\Bitly\Model\CampaignClickData[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'keyword_link' => null,
        'created_ts' => null,
        'bitlink_id' => null,
        'channel_guid' => null,
        'title' => null,
        'campaign_ids' => null,
        'total_clicks' => null,
        'aggregate_link' => null,
        'campaign_guid' => null,
        'link' => null,
        'client_id' => null,
        'long_url' => null,
        'clicks' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'keyword_link' => 'keyword_link',
        'created_ts' => 'created_ts',
        'bitlink_id' => 'bitlink_id',
        'channel_guid' => 'channel_guid',
        'title' => 'title',
        'campaign_ids' => 'campaign_ids',
        'total_clicks' => 'total_clicks',
        'aggregate_link' => 'aggregate_link',
        'campaign_guid' => 'campaign_guid',
        'link' => 'link',
        'client_id' => 'client_id',
        'long_url' => 'long_url',
        'clicks' => 'clicks'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'keyword_link' => 'setKeywordLink',
        'created_ts' => 'setCreatedTs',
        'bitlink_id' => 'setBitlinkId',
        'channel_guid' => 'setChannelGuid',
        'title' => 'setTitle',
        'campaign_ids' => 'setCampaignIds',
        'total_clicks' => 'setTotalClicks',
        'aggregate_link' => 'setAggregateLink',
        'campaign_guid' => 'setCampaignGuid',
        'link' => 'setLink',
        'client_id' => 'setClientId',
        'long_url' => 'setLongUrl',
        'clicks' => 'setClicks'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'keyword_link' => 'getKeywordLink',
        'created_ts' => 'getCreatedTs',
        'bitlink_id' => 'getBitlinkId',
        'channel_guid' => 'getChannelGuid',
        'title' => 'getTitle',
        'campaign_ids' => 'getCampaignIds',
        'total_clicks' => 'getTotalClicks',
        'aggregate_link' => 'getAggregateLink',
        'campaign_guid' => 'getCampaignGuid',
        'link' => 'getLink',
        'client_id' => 'getClientId',
        'long_url' => 'getLongUrl',
        'clicks' => 'getClicks'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['keyword_link'] = $data['keyword_link'] ?? null;
        $this->container['created_ts'] = $data['created_ts'] ?? null;
        $this->container['bitlink_id'] = $data['bitlink_id'] ?? null;
        $this->container['channel_guid'] = $data['channel_guid'] ?? null;
        $this->container['title'] = $data['title'] ?? null;
        $this->container['campaign_ids'] = $data['campaign_ids'] ?? null;
        $this->container['total_clicks'] = $data['total_clicks'] ?? null;
        $this->container['aggregate_link'] = $data['aggregate_link'] ?? null;
        $this->container['campaign_guid'] = $data['campaign_guid'] ?? null;
        $this->container['link'] = $data['link'] ?? null;
        $this->container['client_id'] = $data['client_id'] ?? null;
        $this->container['long_url'] = $data['long_url'] ?? null;
        $this->container['clicks'] = $data['clicks'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['created_ts'] === null) {
            $invalidProperties[] = "'created_ts' can't be null";
        }
        if ($this->container['bitlink_id'] === null) {
            $invalidProperties[] = "'bitlink_id' can't be null";
        }
        if ($this->container['channel_guid'] === null) {
            $invalidProperties[] = "'channel_guid' can't be null";
        }
        if ($this->container['campaign_guid'] === null) {
            $invalidProperties[] = "'campaign_guid' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets keyword_link
     *
     * @return string|null
     */
    public function getKeywordLink()
    {
        return $this->container['keyword_link'];
    }

    /**
     * Sets keyword_link
     *
     * @param string|null $keyword_link keyword_link
     *
     * @return self
     */
    public function setKeywordLink($keyword_link)
    {
        $this->container['keyword_link'] = $keyword_link;

        return $this;
    }

    /**
     * Gets created_ts
     *
     * @return int
     */
    public function getCreatedTs()
    {
        return $this->container['created_ts'];
    }

    /**
     * Sets created_ts
     *
     * @param int $created_ts created_ts
     *
     * @return self
     */
    public function setCreatedTs($created_ts)
    {
        $this->container['created_ts'] = $created_ts;

        return $this;
    }

    /**
     * Gets bitlink_id
     *
     * @return string
     */
    public function getBitlinkId()
    {
        return $this->container['bitlink_id'];
    }

    /**
     * Sets bitlink_id
     *
     * @param string $bitlink_id bitlink_id
     *
     * @return self
     */
    public function setBitlinkId($bitlink_id)
    {
        $this->container['bitlink_id'] = $bitlink_id;

        return $this;
    }

    /**
     * Gets channel_guid
     *
     * @return string
     */
    public function getChannelGuid()
    {
        return $this->container['channel_guid'];
    }

    /**
     * Sets channel_guid
     *
     * @param string $channel_guid channel_guid
     *
     * @return self
     */
    public function setChannelGuid($channel_guid)
    {
        $this->container['channel_guid'] = $channel_guid;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string|null
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string|null $title title
     *
     * @return self
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets campaign_ids
     *
     * @return string[]|null
     */
    public function getCampaignIds()
    {
        return $this->container['campaign_ids'];
    }

    /**
     * Sets campaign_ids
     *
     * @param string[]|null $campaign_ids campaign_ids
     *
     * @return self
     */
    public function setCampaignIds($campaign_ids)
    {
        $this->container['campaign_ids'] = $campaign_ids;

        return $this;
    }

    /**
     * Gets total_clicks
     *
     * @return int|null
     */
    public function getTotalClicks()
    {
        return $this->container['total_clicks'];
    }

    /**
     * Sets total_clicks
     *
     * @param int|null $total_clicks total_clicks
     *
     * @return self
     */
    public function setTotalClicks($total_clicks)
    {
        $this->container['total_clicks'] = $total_clicks;

        return $this;
    }

    /**
     * Gets aggregate_link
     *
     * @return string|null
     */
    public function getAggregateLink()
    {
        return $this->container['aggregate_link'];
    }

    /**
     * Sets aggregate_link
     *
     * @param string|null $aggregate_link aggregate_link
     *
     * @return self
     */
    public function setAggregateLink($aggregate_link)
    {
        $this->container['aggregate_link'] = $aggregate_link;

        return $this;
    }

    /**
     * Gets campaign_guid
     *
     * @return string
     */
    public function getCampaignGuid()
    {
        return $this->container['campaign_guid'];
    }

    /**
     * Sets campaign_guid
     *
     * @param string $campaign_guid campaign_guid
     *
     * @return self
     */
    public function setCampaignGuid($campaign_guid)
    {
        $this->container['campaign_guid'] = $campaign_guid;

        return $this;
    }

    /**
     * Gets link
     *
     * @return string|null
     */
    public function getLink()
    {
        return $this->container['link'];
    }

    /**
     * Sets link
     *
     * @param string|null $link link
     *
     * @return self
     */
    public function setLink($link)
    {
        $this->container['link'] = $link;

        return $this;
    }

    /**
     * Gets client_id
     *
     * @return string|null
     */
    public function getClientId()
    {
        return $this->container['client_id'];
    }

    /**
     * Sets client_id
     *
     * @param string|null $client_id client_id
     *
     * @return self
     */
    public function setClientId($client_id)
    {
        $this->container['client_id'] = $client_id;

        return $this;
    }

    /**
     * Gets long_url
     *
     * @return string|null
     */
    public function getLongUrl()
    {
        return $this->container['long_url'];
    }

    /**
     * Sets long_url
     *
     * @param string|null $long_url long_url
     *
     * @return self
     */
    public function setLongUrl($long_url)
    {
        $this->container['long_url'] = $long_url;

        return $this;
    }

    /**
     * Gets clicks
     *
     * @return \Bitly\Model\CampaignClickData[]|null
     */
    public function getClicks()
    {
        return $this->container['clicks'];
    }

    /**
     * Sets clicks
     *
     * @param \Bitly\Model\CampaignClickData[]|null $clicks clicks
     *
     * @return self
     */
    public function setClicks($clicks)
    {
        $this->container['clicks'] = $clicks;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


