<?php
/**
 * CustomBitlinksApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  Bitly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Bitly API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: api@bitly.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Bitly\Test\Api;

use \Bitly\Configuration;
use \Bitly\ApiException;
use \Bitly\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * CustomBitlinksApiTest Class Doc Comment
 *
 * @category Class
 * @package  Bitly
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomBitlinksApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for addCustomBitlink
     *
     * Add Custom Bitlink.
     *
     */
    public function testAddCustomBitlink()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getClicksForCustomBitlink
     *
     * Get Clicks for a Custom Bitlink's Entire History.
     *
     */
    public function testGetClicksForCustomBitlink()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomBitlink
     *
     * Retrieve Custom Bitlink.
     *
     */
    public function testGetCustomBitlink()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getCustomBitlinkMetricsByDestination
     *
     * Get Metrics for a Custom Bitlink by Destination.
     *
     */
    public function testGetCustomBitlinkMetricsByDestination()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for updateCustomBitlink
     *
     * Update Custom Bitlink.
     *
     */
    public function testUpdateCustomBitlink()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
